services:
  local-postgres-compose:
    image: postgres
    container_name: local-postgres-compose
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "credifacdb"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-boot-app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: credifacapi  # Nome da imagem para o Spring Boot
    ports:
      - "8080:8080"  # Porta do Spring Boot
    networks:
      - postgres-compose-network
    depends_on:
      - local-postgres-compose  # Aguarda o banco de dados iniciar

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  postgres-data:
